### Aula 05 - Mistura de tipos

In [1]:
# Rodar o código apenas uma vez para instalar a biblioteca pandas
# Depois comentar para evitar tentar instalar novamente em execuções futuras
# !pip install pandas

# Importação do pandas para manipulação de dados
import pandas as pd

In [10]:
# Carregando dataframe
df = pd.read_csv('aula_05_dataset.csv')

# Inspeção visual do dataframe
display(df)

   ID_SKU      Nome_Item  Quantidade Localizacao  Ativo
0   SKU01    Parafuso A1        1000     Setor A    Sim
1   SKU02       Prego B2         500     Setor B      1
2   SKU03       Porca C3        2000     Setor A   True
3   SKU04     Arruela D4        1500     Setor C    Não
4   SKU05    Chave Fenda          50     Setor D      0
5   SKU06        Alicate          30     Setor D  False
6   SKU07        Martelo          20     Setor D    Sim
7   SKU08        Serrote          15     Setor E      1
8   SKU09          Trena          40     Setor E   True
9   SKU10          Nível          10     Setor E    Não
10  SKU11      Furadeira           5     Setor F      0
11  SKU12      Broca 8mm         100     Setor F  False
12  SKU13      Bucha 8mm         500     Setor F    Sim
13  SKU14   Lixa Madeira         200     Setor G      1
14  SKU15      Verniz 1L          12     Setor G   True
15  SKU16         Pincel          25     Setor G    Não
16  SKU17         Escada           3     Setor H      0
17  SKU18       Lanterna           8     Setor H  False
18  SKU19       Pilha AA         200     Setor H    Sim
19  SKU20  Fita Isolante          60     Setor I      1

In [9]:
df.replace({"True":1,"False":0,"Sim":1,"Não":0},inplace=True)
display(df)

   ID_SKU      Nome_Item  Quantidade Localizacao Ativo
0   SKU01    Parafuso A1        1000     Setor A     1
1   SKU02       Prego B2         500     Setor B     1
2   SKU03       Porca C3        2000     Setor A     1
3   SKU04     Arruela D4        1500     Setor C     0
4   SKU05    Chave Fenda          50     Setor D     0
5   SKU06        Alicate          30     Setor D     0
6   SKU07        Martelo          20     Setor D     1
7   SKU08        Serrote          15     Setor E     1
8   SKU09          Trena          40     Setor E     1
9   SKU10          Nível          10     Setor E     0
10  SKU11      Furadeira           5     Setor F     0
11  SKU12      Broca 8mm         100     Setor F     0
12  SKU13      Bucha 8mm         500     Setor F     1
13  SKU14   Lixa Madeira         200     Setor G     1
14  SKU15      Verniz 1L          12     Setor G     1
15  SKU16         Pincel          25     Setor G     0
16  SKU17         Escada           3     Setor H     0
17  SKU18       Lanterna           8     Setor H     0
18  SKU19       Pilha AA         200     Setor H     1
19  SKU20  Fita Isolante          60   Setor Sim     1

In [ ]:
df.Ativo.replace({"True":1,"False":0,"Sim":1,"Não":0},inplace=True)
display(df)